### ISSUE TITLE
create token

### ISSUE THREAD

**Issue by vinySan** [open-pay/openpay-dotnet#2]
hi i want to know how can create a token from card

**Comment by marcosAlvarado** [comment]
Hi @vinySan!

To create token you should use our Client-side Libraries.

https://www.openpay.mx/en/docs/libraries.html

Have a nice day!

**Comment by vinySan** [comment]
You have some plugin forma xamarín forms?

**Comment by marcosAlvarado** [comment]
Hi again @vinySan!

Sorry :( , we doesn't have a plugin for xamarin....

But you can see the example here...

https://www.openpay.mx/en/docs/openpayjs.html

Or you could analyze our integration here....

http://demo.openpay.mx/product-detail.jsp?id=2

Source Code:
https://github.com/open-pay/openpay-shopping-sample

**Comment by vinySan** [comment]
thanks for the information,
 I followed your documentation to implement it in xamarin, but it does not allow me to generate a token
` public class Card {
        public string HolderName { get; set; }
        public string Number { get; set; }
        public string ExpirationMonth { get; set; }
        public string ExpirationYear { get; set; }
        public int Cvv2 { get; set; }
        }

        public async void tokei(Object sender, EventArgs e) {
            HttpClient cliente = new HttpClient();
            string url = "https://sandbox-api.openpay.mx/v1/............/tokens";
            var datos = new Card();
            datos.HolderName = "Francisco Pantera";
            datos.Number = "4111111111111111";
            datos.ExpirationMonth = "12";
            datos.ExpirationYear = "21";
            datos.Cvv2 = 123;
            String create = JsonConvert.SerializeObject(datos);
            var content = new StringContent(create, Encoding.UTF8, "application/json");
            var resultado = await cliente.PostAsync(url, content);
            var res = resultado.Content.ReadAsStringAsync().Result;
            await DisplayAlert("dato:", res, "aceptar");
        }`


send an exception, the message says a task was canceled

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

Hopefully you're not having this issue anymore but if there are problems still happening please let us know and we'll open this issue again.

Cheers!
