### ISSUE TITLE
Please specify a valid source_id

### ISSUE THREAD

**Issue by GabyPablosLopez** [open-pay/openpay-dotnet#3]
Estoy teniendo bastantes problemas al realizar cargo utilizando idCard de una tarjeta ya creada y asignada a un customer. La tarjeta se crea en front con js, en back asigno esa tarjeta a un customer que creo, y al realizar cargo me aparece ese error.
Espero su pronta respuesta, ya que tengo bastante con este error.
Lo que envío es lo siguiente:

{
    "method": "card",
    "source_id": "kz7pvzgbx3vjcxoflbvv",
    "amount": 1.0,
    "description": "Cargo Tarjeta Crédito - Inst 1",
    "capture": true,
    "device_session_id": "O76h4ppTx6qDS6sLqyDBT7dE0hRyqZtV",
    "customer": {
        "name": "GABRIELA LOPEZ",
        "email": "xxxxxx@xxx.xx",
        "balance": 0.0,
        "creation_date": "2018-08-27T15:22:32-05:00",
        "requires_account": false,
        "id": "aipffgy7izdxfmswz7lr"
    },
    "confirm": true,
    "send_email": false,
    "use_3d_secure": false
}

**Comment by GabyPablosLopez** [comment]
El source_id que asigno, es el id de una tarjeta previamente asignada a un cliente. Si mando el token directamente si realiza el cargo, pero no funciona con el card_id. 
Agradecería mucho su apoyo

**Comment by ecarloslr** [comment]
Hola, me parece que el problema podría ser la ruta a la que se envía la petición. Si el token se asignó a un cliente que tiene un Customer ID, hay que indicar el Customer ID en el método de cargo, y no especificar el campo customer en la petición:

`Charge charge = openpayAPI.ChargeService.Create("aipffgy7izdxfmswz7lr", request);`

Para que se envíe a la ruta:

> /v1/{MERCHANT_ID}/customers/{CUSTOMER_ID}/charges

**Comment by GabyPablosLopez** [comment]
Muchas Gracias @ecarloslr , tu respuesta me ayudó a resolver el problema:
            ChargeRequest request = new ChargeRequest();
            request.Method = "card";
            request.SourceId = "kz7pvzgbx3vjcxoflbvv";
            request.DeviceSessionId = datosTarjeta.DeviceSessionId;
            request.Description = "Cargo Tarjeta Crédito - Inst " + cveInstitucion;
            request.Amount = new Decimal(monto);
            request.Currency = "MXN";
            Charge charge = api.ChargeService.Create("aipffgy7izdxfmswz7lr", request);
