### ISSUE TITLE
Error System.TypeLoadException

### ISSUE THREAD

**Issue by Kaatelars** [open-pay/openpay-dotnet#5]
Recientemente tuve la necesidad de incorporar Openpay a mi sistema. Al hacer la instalación del Nuget a mi sistema y comenzar a hacer pruebas, me encuentro con el siguiente error al compilar:
System.TypeLoadException: 'No se puede cargar el tipo 'Openpay.OpenpayAPI' del ensamblado'Openpay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'
![issuevs](https://user-images.githubusercontent.com/15205939/50497877-63602080-0a01-11e9-8422-cead2252e7f7.JPG)

¿Cómo puedo solventar este error?

**Comment by jemy-dasm-openpay** [comment]
Cerramos este issue por la antigüedad del mismo.
En caso de que aun persistieran los problemas podríamos reabrirlo para su revisión.

¡Saludos!
